from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
doc = Document('BTP_Report_Ch3.docx')
for s in doc.sections: s.top_margin=Inches(1); s.bottom_margin=Inches(1); s.left_margin=Inches(1.5); s.right_margin=Inches(1)
def H(t,sz=14,al=WD_ALIGN_PARAGRAPH.LEFT):
    p=doc.add_paragraph(); p.alignment=al; r=p.add_run(t); r.bold=True; r.font.size=Pt(sz); r.font.name='Times New Roman'
def P(t):
    p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.JUSTIFY; p.paragraph_format.space_after=Pt(6); r=p.add_run(t); r.font.size=Pt(12); r.font.name='Times New Roman'
def NL(): p=doc.add_paragraph(); p.paragraph_format.space_before=Pt(0); p.paragraph_format.space_after=Pt(0)

H("CHAPTER 4",16,WD_ALIGN_PARAGRAPH.CENTER)
H("RESULTS AND DISCUSSION",14,WD_ALIGN_PARAGRAPH.CENTER)
NL()

H("4.1  Case Study Configuration")
P("To evaluate the proposed framework, a case study was conducted for the location Greater Noida, India, using the developed frontend-backend analysis platform. The geographical location was selected through the user interface, and the simulation date was fixed as 13 March 2026 in order to obtain location-specific solar irradiance data for that day. A parametric sweep was performed over a range of geometric configurations as described below.")
P("The module mounting height was varied from 50 cm to 450 cm with increments of 50 cm, while the tilt angle was varied from 10 degrees to 50 degrees in steps of 10 degrees. The azimuth angle of the PV module was fixed at 180 degrees for south-facing panels, which is the standard orientation for photovoltaic installations in the northern hemisphere to maximize solar exposure. The bifaciality factor was assumed to be 0.7, which is a practical value for modern bifacial modules. The ground surface type was selected as concrete, corresponding to an albedo value of 0.3. The Nominal Operating Cell Temperature (NOCT) was maintained at 45 degrees Celsius.")
P("The irradiance was fetched using the NASA POWER API, and the observed total GHI for the selected date was 6.08 kWh/m2 with a peak GHI of 866.53 Wh/m2. These values are consistent with the expected solar resource availability for the Greater Noida region during the month of March, confirming the reliability of the data retrieval process.")

H("4.2  Combined Parametric Sweep Results")
P("The parametric analyses were executed using the MATLAB engine incorporating the mathematical formulation discussed in Chapter 3. A total of 45 evaluation points (9 height levels x 5 tilt angle levels) were computed for the concrete surface (albedo = 0.3). For each evaluation point, the framework calculated the total energy output, peak power, and rear gain percentage.")
P("The optimal configuration among the 45 evaluation points was identified based on the maximum energy optimization objective. The results indicated an optimal tilt angle of 30 degrees and a mounting height of 450 cm for the selected albedo value of 0.3 (concrete surface). At this optimal configuration, the rear gain was computed to be 16.55% using equation (11). This result demonstrates that a properly configured bifacial PV installation at the selected location can achieve substantial additional energy generation from the rear surface compared to an equivalent monofacial installation.")

H("4.3  I-V and P-V Characteristics")
P("The current-voltage (I-V) and power-voltage (P-V) characteristics were plotted for the various parameter-based configurations analyzed in the sweep. The I-V curves illustrate the variation in short-circuit current and open-circuit voltage across different installation configurations, reflecting the changes in effective irradiance received by the bifacial module under each scenario.")
P("The P-V curves clearly show the shift in maximum power point (MPP) as the installation parameters are varied. Configurations with higher effective irradiance (resulting from optimal tilt, height, and albedo combinations) exhibit higher peak power values on the P-V curve. The graphical representation of these characteristics provides a visual confirmation of the parametric analysis results and enables the system designer to assess the electrical performance implications of different installation choices.")
P("[Figure 4.1: I-V characteristics for different configurations - Insert graph here]")
P("[Figure 4.2: P-V characteristics for different configurations - Insert graph here]")

H("4.4  Optimal Configuration: Maximum Energy")
P("Table 4.1 presents the top five configurations ranked by maximum energy output. The optimization objective in this case is to maximize the total energy generated by the bifacial PV system over the analysis period.")

H("Table 4.1: Max Energy Based Optimal Configuration",12)
tbl = doc.add_table(rows=6, cols=6)
tbl.style = 'Table Grid'
hdr = ["Rank","Height (cm)","Tilt (deg)","Surface","Energy (kWh)","Rear Gain (%)"]
for j,h in enumerate(hdr):
    c=tbl.cell(0,j); c.text=h
    for p in c.paragraphs:
        for r in p.runs: r.bold=True; r.font.name='Times New Roman'; r.font.size=Pt(10)
data=[
    ["1","450","30","Concrete","3.16843","16.5518"],
    ["2","450","40","Concrete","3.16570","15.6057"],
    ["3","400","30","Concrete","3.16521","16.3917"],
    ["4","400","40","Concrete","3.16258","15.4506"],
    ["5","350","30","Concrete","3.16113","16.1891"],
]
for i,row in enumerate(data):
    for j,v in enumerate(row):
        c=tbl.cell(i+1,j); c.text=v
        for p in c.paragraphs:
            for r in p.runs: r.font.name='Times New Roman'; r.font.size=Pt(10)

P("The results show that the highest energy output of 3.168 kWh is achieved at a height of 450 cm and tilt angle of 30 degrees with the concrete surface. The top configurations consistently favor heights of 350-450 cm and tilt angles of 30-40 degrees. The rear gain percentages for the top energy configurations range from 15.45% to 16.55%, indicating significant contribution from the rear surface.")

H("4.5  Optimal Configuration: Maximum Rear Gain")
P("Table 4.2 presents the top five configurations ranked by maximum rear gain percentage. This optimization objective prioritizes maximizing the relative contribution of the rear surface to the total energy output.")

H("Table 4.2: Max Rear Gain Based Optimal Configuration",12)
tbl2 = doc.add_table(rows=6, cols=6)
tbl2.style = 'Table Grid'
for j,h in enumerate(hdr):
    c=tbl2.cell(0,j); c.text=h
    for p in c.paragraphs:
        for r in p.runs: r.bold=True; r.font.name='Times New Roman'; r.font.size=Pt(10)
data2=[
    ["1","450","10","Concrete","2.99422","17.8989"],
    ["2","400","10","Concrete","2.99130","17.7561"],
    ["3","350","10","Concrete","2.98755","17.5731"],
    ["4","300","10","Concrete","2.98258","17.3301"],
    ["5","450","20","Concrete","3.11109","17.3252"],
]
for i,row in enumerate(data2):
    for j,v in enumerate(row):
        c=tbl2.cell(i+1,j); c.text=v
        for p in c.paragraphs:
            for r in p.runs: r.font.name='Times New Roman'; r.font.size=Pt(10)

P("When the optimization objective is shifted to maximum rear gain, a different set of optimal configurations emerges. The highest rear gain of 17.90% is achieved at a height of 450 cm and a lower tilt angle of 10 degrees. This is because lower tilt angles increase the ground view factor for the rear surface, allowing more ground-reflected radiation to reach the rear side of the module. However, the total energy output for these configurations (2.994 kWh) is lower compared to the maximum energy configurations (3.168 kWh), illustrating the trade-off between total energy maximization and rear gain maximization. The PV system designer can choose the appropriate optimization objective based on their specific requirements.")

H("4.6  Individual Parameter Variation Analysis")
P("In addition to the combined parametric sweep, the framework provides a provision for fixing two parameters and varying the third to obtain focused analyses of individual parameter effects. This feature makes the platform dynamic and adaptable to the practical needs of PV system designers.")

H("4.6.1  Effect of Albedo Variation",12)
P("Figure 4.4 shows the variation of rear share of effective irradiance when varying the albedo (surface type) with the following fixed parameters: tilt angle of 20 degrees, height of 100 cm, azimuthal angle of 180 degrees, and bifaciality of 0.7. The results demonstrate that the rear gain share increases monotonically with increasing albedo value. The highest rear gain share of 24.72% was achieved for the aluminum surface (albedo = 0.85), confirming the strong dependence of rear-side performance on ground surface reflectivity. Low-albedo surfaces such as dry asphalt (albedo approximately 0.12) produced rear gain values below 5%, while moderate-albedo surfaces such as concrete (albedo approximately 0.30) yielded intermediate values. These findings are consistent with the results reported by Dincer and Ozer [11], who found that aluminum surfaces provided the highest rear-surface energy generation of 21.2%, and by Ganesan et al. who reported an average bifacial gain of 21.4% from aluminum surfaces.")
P("[Figure 4.4: Rear share of effective irradiance on varying albedo - Insert graph here]")

H("4.6.2  Effect of Height Variation",12)
P("Figure 4.5 illustrates the variation of rear share of effective irradiance when varying the panel height with the tilt angle fixed at 20 degrees, albedo of 0.18, and all other factors remaining the same. The results show that rear gain increases with panel height, achieving 6.61% for a panel height of 100 cm. The rate of increase diminishes at higher elevations, consistent with the near-logarithmic dependence of rear-side performance on module elevation demonstrated by Yusufoglu et al. [18]. This behavior is expected because the geometric view factor between the module and the ground improves with height but approaches an asymptotic limit as the module elevation increases beyond a certain threshold relative to the module dimensions.")
P("[Figure 4.5: Rear share of effective irradiance on varying height - Insert graph here]")

H("4.6.3  Effect of Tilt Angle Variation",12)
P("Figure 4.6 presents the variation of rear share of effective irradiance when varying the tilt angle with the height fixed at 100 cm, albedo of 0.18, and all other factors remaining the same. The results indicate a maximum rear gain share of 7.24% at a tilt angle of 10 degrees. The rear gain decreases with increasing tilt angle in this configuration, which can be attributed to the change in balance between sky view and ground view factors. At lower tilt angles, the ground view factor for the rear surface is larger, allowing more ground-reflected radiation to reach the rear side. As the tilt angle increases, the rear sky view factor decreases, reducing the effective rear irradiance. This finding is consistent with the observations reported in the literature, where the interaction between front-side and rear-side performance creates a complex optimization landscape for bifacial modules.")
P("[Figure 4.6: Rear share of effective irradiance on varying tilt angle - Insert graph here]")

H("4.7  Comparison with Published Literature")
P("To validate the proposed framework, the results obtained in this study were compared with findings reported in published literature.")

H("Table 4.3: Comparison with Published Literature",12)
tbl3 = doc.add_table(rows=5, cols=4)
tbl3.style = 'Table Grid'
ch=["Study","Scenario","Reported (%)","This Study (%)"]
for j,h in enumerate(ch):
    c=tbl3.cell(0,j); c.text=h
    for p in c.paragraphs:
        for r in p.runs: r.bold=True; r.font.name='Times New Roman'; r.font.size=Pt(10)
cd=[
    ["Dincer & Ozer [11]","Aluminum, Tilt:20, H:100cm","21.2","24.72"],
    ["Dincer & Ozer [11]","Height 40-100cm, Urban","4.1-4.5","5.2-6.6"],
    ["Yusufoglu et al. [18]","alpha=0.2, 2m height","13.8 gain","16.55"],
    ["Ganesan et al.","Aluminum, bifacial gain","21.4","24.72"],
]
for i,row in enumerate(cd):
    for j,v in enumerate(row):
        c=tbl3.cell(i+1,j); c.text=v
        for p in c.paragraphs:
            for r in p.runs: r.font.name='Times New Roman'; r.font.size=Pt(10)

P("The comparison reveals that the results obtained using the proposed framework are consistent with the trends and magnitudes reported in the reference studies. Minor differences in absolute values are attributable to variations in geographic location, solar irradiance characteristics, assumed panel parameters, and modeling methodology. The overall agreement validates the reliability and accuracy of the proposed computational framework for bifacial PV system optimization.")

H("4.8  Discussion of Results")
P("The parametric analysis results provide several important insights for the design and optimization of bifacial PV installations. First, the analysis confirms that ground surface albedo is the most influential parameter affecting rear-side irradiance contribution. The rear gain varied from less than 5% for low-albedo surfaces to over 24% for highly reflective surfaces, representing a variation of nearly five-fold. This finding has direct practical implications, suggesting that site preparation measures such as installing reflective ground cover materials can substantially improve the performance of bifacial PV systems.")
P("Second, the results demonstrate that mounting height has a positive but diminishing effect on rear-side performance. While higher installations consistently yield higher rear gains, the incremental improvement decreases with increasing elevation. This suggests that there exists a practical optimum height beyond which the additional structural costs and complexity of higher mounting systems cannot be justified by the marginal energy gains.")
P("Third, the analysis reveals that the optimal tilt angle depends on the chosen optimization objective. When maximizing total energy, the optimal tilt angle (30 degrees for Greater Noida) closely corresponds to the latitude of the installation site, similar to monofacial modules. However, when maximizing rear gain, lower tilt angles (10-20 degrees) are preferred due to their enhanced ground view factor for the rear surface. This dual optimization capability of the proposed framework enables system designers to make informed decisions based on their specific priorities.")
P("Fourth, the combined parametric sweep approach adopted in this work provides a more comprehensive optimization compared to single-parameter studies. The interaction effects between tilt angle, height, and albedo are captured in the multi-dimensional analysis, leading to more accurate identification of globally optimal configurations.")
doc.add_page_break()

# CHAPTER 5
H("CHAPTER 5",16,WD_ALIGN_PARAGRAPH.CENTER)
H("CONCLUSION AND FUTURE WORK",14,WD_ALIGN_PARAGRAPH.CENTER)
NL()

H("5.1  Summary of Contributions")
P("This project has presented a comprehensive computational framework for the parametric analysis and optimization of bifacial photovoltaic systems. The key contributions of this work can be summarized as follows:")
P("1. A rigorous mathematical model for computing the front-side and rear-side irradiance on bifacial PV modules has been implemented, incorporating the Liu-Jordan isotropic sky model for front-side irradiance estimation and the Yusufoglu view factor approach for accurate rear-side irradiance calculation with shadow correction.")
P("2. A MATLAB/Simulink model has been developed for simulating the electrical characteristics (I-V and P-V curves) of bifacial PV modules under varying irradiance and temperature conditions.")
P("3. A user-oriented frontend platform has been designed and implemented that integrates location-based solar irradiance data retrieval from the NASA POWER API with automated parametric sweep analyses, providing an accessible tool for PV system designers.")
P("4. The framework supports dual optimization objectives (maximum energy and maximum rear gain), enabling system designers to evaluate trade-offs and make informed configuration decisions.")
P("5. The proposed approach has been validated through a case study for Greater Noida, India, with results showing good agreement with published literature.")

H("5.2  Key Findings")
P("The parametric analyses conducted in this study have yielded the following key findings:")
P("1. For the case study location (Greater Noida, India) with a concrete ground surface (albedo = 0.3), the optimal configuration for maximum energy output was identified as a tilt angle of 30 degrees and mounting height of 450 cm, achieving a total energy of 3.168 kWh and rear gain of 16.55%.")
P("2. The optimal configuration for maximum rear gain was a tilt angle of 10 degrees and height of 450 cm, achieving a rear gain of 17.90% but with a lower total energy of 2.994 kWh.")
P("3. Ground surface albedo was confirmed as the most influential parameter affecting rear-side irradiance contribution, with rear gain varying from below 5% for low-albedo surfaces to over 24% for highly reflective surfaces such as aluminum.")
P("4. Mounting height has a positive but diminishing effect on rear-side performance, consistent with the near-logarithmic dependence reported in the literature.")
P("5. The interaction between tilt angle, height, and albedo necessitates combined parametric optimization rather than independent single-parameter studies.")

H("5.3  Limitations")
P("The present work has certain limitations that should be acknowledged. First, the mathematical model assumes uniform ground albedo beneath the module, which may not accurately represent real-world installations where ground surface properties can vary spatially. Second, the analysis is based on single-day irradiance data; extending the analysis to annual energy yield computations would provide more comprehensive optimization results. Third, the current implementation does not account for inter-row shading effects in multi-row array configurations, which can be significant in large-scale installations. Fourth, temperature effects on module performance are modeled using the simplified NOCT approach, and more detailed thermal models may improve the accuracy of energy yield predictions.")

H("5.4  Scope for Future Work")
P("Several directions for future research and development are identified based on the outcomes of this project:")
P("1. Extension to Annual Energy Yield: The current framework can be extended to perform year-round energy yield simulations by aggregating daily analyses across all days of the year, providing more comprehensive optimization guidance for long-term system design.")
P("2. Multi-Row Array Modeling: Incorporating inter-row shading models would enable the framework to optimize row-to-row spacing in addition to tilt, height, and albedo, making it applicable to utility-scale bifacial solar farm design.")
P("3. Machine Learning Integration: Developing machine learning models trained on the parametric sweep data could enable rapid prediction of optimal configurations without requiring full computational analysis, significantly reducing the optimization time for new locations.")
P("4. Economic Analysis: Integrating techno-economic analysis capabilities would allow the framework to evaluate the cost-effectiveness of different bifacial PV configurations, accounting for structural costs, ground preparation costs, and the economic value of additional energy generation.")
P("5. Real-Time Monitoring: Developing a real-time monitoring system that continuously compares actual system performance with predicted values could enable adaptive optimization and early detection of performance degradation.")
P("6. Geographic Information System Integration: Combining the optimization framework with GIS tools could enable automated site assessment for large-scale bifacial PV deployment planning, incorporating terrain, land use, and local albedo mapping data.")

doc.add_page_break()

# REFERENCES
H("REFERENCES",16,WD_ALIGN_PARAGRAPH.CENTER)
NL()
refs = [
    '[1] R. Guerrero-Lemus, F. Vega, E. Kim, A. Kimm and M. Shephard, "Bifacial solar photovoltaics - A technology review," Renewable and Sustainable Energy Reviews, vol. 60, pp. 1533-1549, 2016.',
    '[2] M. Alam, M. R. Khan and C. Deline, "Performance comparison between bifacial and monofacial photovoltaic systems under varying environmental conditions," Sustainable Energy Technologies and Assessments, vol. 57, p. 103210, 2023.',
    '[3] C. Deline, A. A. Pelaez, S. MacAlpine and B. Marion, "Bifacial photovoltaic system performance: Separating fact from fiction," National Renewable Energy Laboratory (NREL), Golden, CO, USA, 2019.',
    '[4] X. Sun, M. R. Khan, C. Deline and M. A. Alam, "Optimization and performance of bifacial solar modules: A global perspective," Applied Energy, vol. 212, pp. 1601-1610, 2018.',
    '[5] A. Basak, S. Das and R. Banerjee, "Tilt angle optimization for bifacial photovoltaic modules for enhanced energy generation," Applied Energy, vol. 345, p. 121245, 2025.',
    '[6] U. Peter and M. Novak, "Optimal tilt angle for maximizing energy production of bifacial solar panels," Journal of Sustainable Energy Systems, vol. 14, no. 1, pp. 45-56, 2025.',
    '[7] N. Riedel-Lyngskjaer, J. M. L. P. Larsen and B. G. Nielsen, "Effect of spectral albedo on energy yield of bifacial photovoltaic systems," Solar Energy, vol. 231, pp. 176-186, 2022.',
    '[8] M. H. Aksoy and H. A. Ceylan, "Investigation of ground albedo effects on bifacial photovoltaic panel performance," Renewable Energy Research Journal, vol. 13, no. 4, pp. 1800-1808, 2023.',
    '[9] N. Baghel, A. Chandel and S. K. Sharma, "Performance evaluation and optimization of albedo and tilt angle in bifacial photovoltaic systems," Solar Energy, vol. 250, pp. 84-95, 2023.',
    '[10] I. N. Atalay, M. Kaya and H. Ozturk, "Experimental investigation of ground surface reflectivity impact on bifacial photovoltaic systems," Solar Energy, vol. 246, pp. 65-74, 2023.',
    '[11] F. Dincer and E. Ozer, "Optimization of rear-side energy contribution in bifacial PV panels: A parametric analysis on albedo, tilt, height, and mounting configuration," Energies, vol. 18, p. 4443, 2025.',
    '[12] D. S. Braga, R. Zilles and E. Lorenzo, "Performance analysis of bifacial photovoltaic modules under tropical climatic conditions," Renewable Energy and Environmental Sustainability, vol. 8, pp. 1-10, 2023.',
    '[13] A. F. Almarshoud, A. Al-Badi and M. Al-Sulaiman, "Experimental performance analysis of bifacial photovoltaic modules under different operating conditions," Energies, vol. 17, no. 21, p. 5456, 2024.',
    '[14] M. T. Patel, M. R. Khan and M. A. Alam, "Optimum design of tracking bifacial solar farms," IEEE Journal of Photovoltaics, vol. 11, no. 1, pp. 237-245, 2021.',
    '[15] B. Y. H. Liu and R. C. Jordan, "The interrelationship and characteristic distribution of direct, diffuse and total solar radiation," Solar Energy, vol. 4, pp. 1-19, 1960.',
    '[16] J. A. Duffie and W. A. Beckman, Solar Engineering of Thermal Processes, Hoboken, NJ, USA: Wiley, 2013.',
    '[17] B. Marion, C. Deline, A. A. Pelaez, S. MacAlpine and B. Stein, "A practical irradiance model for bifacial PV modules," IEEE Journal of Photovoltaics, vol. 7, no. 1, pp. 1-7, 2017.',
    '[18] U. A. Yusufoglu, T. M. Pletzer, H. H. Kurz and H. J. Hubner, "Simulation of energy production by bifacial modules with revision of ground reflection," Energy Procedia, vol. 55, pp. 389-395, 2014.',
    '[19] P. K. Sahu, J. N. Roy and C. Chakraborty, "Performance assessment of a bifacial PV system using a new energy estimation model," Solar Energy, vol. 262, p. 111818, 2023.',
    '[20] K. Ganesan, D. P. Winston, S. Sugumar and S. Jegan, "Performance analysis of n-type PERT bifacial solar PV module under diverse albedo conditions," Solar Energy, vol. 252, pp. 81-90, 2023.',
    '[21] S. A. Pelaez, C. Deline, S. M. MacAlpine, B. Marion, J. S. Stein and R. K. Kostuk, "Comparison of bifacial solar irradiance model predictions with field validation," IEEE Journal of Photovoltaics, vol. 9, pp. 82-88, 2018.',
    '[22] C. Ghenai, F. F. Ahmad, O. Rejeb and A. K. Hamid, "Sensitivity analysis of design parameters and power gain correlations of bi-facial solar PV system using response surface methodology," Solar Energy, vol. 223, pp. 44-53, 2021.',
]
for ref in refs:
    P(ref)

doc.add_page_break()

# APPENDIX
H("APPENDIX A",16,WD_ALIGN_PARAGRAPH.CENTER)
H("Software Code Excerpts",14,WD_ALIGN_PARAGRAPH.CENTER)
NL()
P("[Insert relevant code excerpts for the irradiance calculation module, frontend interface code, and backend API integration code here.]")
doc.add_page_break()
H("APPENDIX B",16,WD_ALIGN_PARAGRAPH.CENTER)
H("Simulink Block Diagrams",14,WD_ALIGN_PARAGRAPH.CENTER)
NL()
P("[Insert Simulink model screenshots and block diagram details here.]")
doc.add_page_break()

# BIO-DATA
H("BIO-DATA",16,WD_ALIGN_PARAGRAPH.CENTER)
NL()
for name, roll in [("Ashish Upadhyay","2022UEE4521"),("Pratyai Chakrabarty","2022UEE4586"),("Aman","2022UEE4532"),("Aditya Garg","2022UEE4503")]:
    H(f"{name} ({roll})",12)
    P(f"B.Tech. Student, Department of Electrical Engineering, Netaji Subhas University of Technology (NSUT), Dwarka, New Delhi - 110078")
    NL()

# Save final
doc.save('BTP_Final_Report.docx')
print("FINAL REPORT SAVED: BTP_Final_Report.docx")
