from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH as A
doc=Document('_part1.docx')
for s in doc.sections: s.top_margin=Inches(1);s.bottom_margin=Inches(1);s.left_margin=Inches(1.5);s.right_margin=Inches(1)
def H(t,sz=14,al=A.LEFT):
    p=doc.add_paragraph();p.alignment=al;p.paragraph_format.space_before=Pt(12);p.paragraph_format.space_after=Pt(6);r=p.add_run(t);r.bold=True;r.font.size=Pt(sz);r.font.name='Times New Roman'
def P(t,al=A.JUSTIFY):
    p=doc.add_paragraph();p.alignment=al;p.paragraph_format.space_after=Pt(6);p.paragraph_format.space_before=Pt(3);r=p.add_run(t);r.font.size=Pt(12);r.font.name='Times New Roman'
def NL():
    p=doc.add_paragraph();p.paragraph_format.space_before=Pt(0);p.paragraph_format.space_after=Pt(0)
def TBL(headers,rows,caption=None):
    if caption: H(caption,12,A.CENTER)
    t=doc.add_table(rows=len(rows)+1,cols=len(headers));t.style='Table Grid'
    for j,h in enumerate(headers):
        c=t.cell(0,j);c.text='';cp=c.paragraphs[0];cp.alignment=A.CENTER;r=cp.add_run(h);r.bold=True;r.font.name='Times New Roman';r.font.size=Pt(10)
    for i,row in enumerate(rows):
        for j,v in enumerate(row):
            c=t.cell(i+1,j);c.text='';cp=c.paragraphs[0];cp.alignment=A.CENTER;r=cp.add_run(str(v));r.font.name='Times New Roman';r.font.size=Pt(10)

H("CHAPTER 2",16,A.CENTER);H("LITERATURE REVIEW",14,A.CENTER);NL()
H("2.1  Review of Bifacial PV Technology")
P("Bifacial photovoltaic technology has undergone significant evolution since its conceptual introduction in the 1960s and the first industrial production of bifacial PV panels in 1984. The technology has gained increasing commercial traction in recent years, with market projections indicating that bifacial modules could capture approximately 35% of the global PV market by 2027. This growing market share is driven by the inherent ability of bifacial modules to generate additional electricity from the rear surface without requiring a proportional increase in installation area or balance-of-system components.")
P("Guerrero-Lemus et al. [1] provided a comprehensive review of bifacial solar photovoltaic technology, covering the historical development, cell architectures, and performance characteristics of bifacial modules. Their review highlighted that rear-side irradiance contribution is strongly influenced by environmental and geometric parameters including ground reflectivity, module tilt angle, and installation height. The study also identified the need for standardized testing and characterization protocols for bifacial modules, as the existing IEC standards were primarily designed for monofacial module evaluation.")
P("Alam et al. [2] conducted a detailed performance comparison between bifacial and monofacial photovoltaic systems under varying environmental conditions. Their investigation demonstrated that bifacial systems consistently outperformed monofacial counterparts across diverse climatic scenarios, with the magnitude of improvement dependent on the local irradiance conditions and installation configuration. The study reinforced the importance of site-specific analysis for quantifying the expected benefits of bifacial technology and highlighted that the bifacial advantage is more pronounced in locations with high diffuse radiation fractions.")
P("Deline et al. [3] from the National Renewable Energy Laboratory (NREL) presented an important study on separating fact from fiction in bifacial PV system performance. Their work provided empirical evidence to validate the performance claims associated with bifacial technology and established benchmarks for expected energy yield improvements under various installation conditions. The NREL study emphasized the importance of accurate rear-side irradiance modeling and highlighted common sources of error in bifacial performance predictions.")
P("Sun et al. [4] undertook a global perspective analysis of the optimization and performance of bifacial solar modules. Their study evaluated the combined effects of tilt angle, albedo, and latitude on system performance across diverse geographic locations and demonstrated that bifacial modules offer significant energy yield improvements when properly configured. The research highlighted the importance of considering location-specific solar resource characteristics in optimizing bifacial PV system design and provided valuable reference data for subsequent optimization studies.")

H("2.2  Influence of Tilt Angle on Bifacial PV Performance")
P("The tilt angle of a PV module is a fundamental design parameter that determines the angle of incidence of solar radiation on the module surface. For monofacial modules, the optimal tilt angle is primarily governed by the latitude of the installation site, with adjustments for local climatic conditions and the desired seasonal energy distribution. For bifacial modules, however, the tilt angle optimization becomes more complex due to its simultaneous influence on both front-side and rear-side irradiance capture.")
P("Basak et al. [5] investigated tilt angle optimization specifically for bifacial photovoltaic modules, demonstrating that the optimal tilt angle for bifacial modules may differ from that of monofacial modules due to the additional contribution of ground-reflected radiation to the rear surface. Their study showed that increasing the tilt angle beyond the latitude-optimal value can enhance rear-side performance, although this may come at the cost of reduced front-side irradiance capture. The trade-off between these competing effects creates a complex optimization landscape that depends on the specific installation conditions.")
P("Peter and Novak [6] examined the optimal tilt angle for maximizing energy production of bifacial solar panels. Their findings indicated that the interplay between front-side and rear-side irradiance components creates a more nuanced optimization problem for bifacial modules compared to monofacial systems. The study recommended that tilt angle optimization for bifacial installations should account for both direct and reflected radiation components, as well as the geographic location and local albedo characteristics.")
P("Yusufoglu et al. [18] presented a seminal simulation study examining the annual energy yield of south-facing bifacial modules with rigorous calculation of ground-reflected radiation reaching the rear module surface. Their work demonstrated that optimum tilt angles of bifacial modules depend on a larger set of parameters than standard modules, requiring the albedo coefficient and installation height to be taken into account. They found that at low module elevations, the distance between shadows and modules is shorter, and this drawback can be reduced by increasing tilt angles. They showed differences in optimum tilt angle of 3 to 5 degrees between standard and bifacial modules depending on location and albedo coefficient. At higher albedo coefficients (0.5), the difference in optimum tilt angle for standard and bifacial modules vanishes because the ground reflection grows significantly. This work provided key insights into the view factor calculation methodology adopted in the present study.")

H("2.3  Effect of Ground Albedo on Rear-Side Irradiance")
P("Ground surface albedo is widely recognized as the most influential parameter affecting the rear-side energy contribution of bifacial PV systems. The albedo coefficient quantifies the fraction of incident solar radiation reflected by a surface, with values ranging from near zero for highly absorptive surfaces to values approaching unity for highly reflective surfaces.")
P("Riedel-Lyngskjaer et al. [7] investigated the effect of spectral albedo on the energy yield of bifacial photovoltaic systems. Their study highlighted that the spectral characteristics of reflected radiation, in addition to the overall albedo magnitude, can influence the electrical output of bifacial modules due to the wavelength-dependent response of silicon solar cells. This finding adds another dimension to the albedo optimization problem that is often overlooked in simplified models.")
P("Aksoy and Ceylan [8] conducted an investigation of ground albedo effects on bifacial photovoltaic panel performance, providing quantitative data on the relationship between ground surface type and rear-side energy generation. Baghel et al. [9] performed a comprehensive performance evaluation examining both albedo and tilt angle in bifacial systems, demonstrating synergistic effects of these two parameters. Atalay et al. [10] conducted experimental investigations providing valuable empirical data on actual albedo values achievable with various ground surface types under realistic operating conditions.")
P("Dincer and Ozer [11] presented a comprehensive parametric analysis investigating the optimization of rear-side energy contribution in bifacial PV panels. Their study systematically evaluated four key parameters: albedo, tilt angle, panel height, and mounting configuration. Using experimentally measured GHI data from Turkey, they found that aluminum surfaces provided the highest rear-surface energy generation of 21.2%, followed by fresh snow at 20.5%. Their analysis demonstrated that increasing the tilt angle from 10 degrees to 50 degrees led to a gradual rise in rear-side gain from 4.3% to 5.5%. For panel height variation, the gain increased from 4.1% at 40 cm to 4.5% at 100 cm. They also compared horizontal and vertical mounting configurations, finding horizontal mounting provided a slightly higher rear-side energy yield of 4.5% compared to 4.1% for vertical mounting. This study serves as a primary reference for the parametric analysis approach adopted in the present work.")

H("2.4  Impact of Mounting Height on Energy Yield")
P("The height at which bifacial PV modules are mounted above the ground directly affects the geometric relationship between the module and the reflective ground, influencing the amount of ground-reflected radiation reaching the rear surface.")
P("Yusufoglu et al. [18] provided critical insights into the influence of module elevation through their simulation study. They demonstrated that annual energy yield exhibits a near-logarithmic dependence on module elevation, with the benefit being more pronounced for locations with more direct radiation (such as Cairo) compared to locations with predominantly diffuse radiation (such as Oslo). Their simulations showed that at optimum tilt angles, produced annual energy can be increased by up to 30% compared to a standard module simply by positioning modules two meters above ground instead of close-to-ground installation. Furthermore, they demonstrated a linear relationship between albedo coefficient and annual energy yield for all module elevation heights, with the largest slope obtained for the highest module elevation since higher installations diminish the shadow area allowing the benefit of a more reflective ground to be utilized to a larger extent.")
P("Braga et al. [12] examined the performance of bifacial PV modules under tropical climatic conditions, providing valuable data on the interaction between mounting height and tropical solar geometry. Almarshoud et al. [13] conducted experimental performance analysis confirming the positive correlation between module elevation and rear-side energy contribution, while highlighting practical constraints that limit feasible mounting heights in real installations.")

H("2.5  Combined Parametric Optimization Studies")
P("While many studies have examined individual parameters in isolation, a growing body of research has recognized the importance of evaluating combined effects of multiple parameters on bifacial PV system performance.")
P("Patel et al. [14] addressed the optimum design of tracking bifacial solar farms, demonstrating that multiple parameters including module orientation, mounting height, and system geometry must be optimized simultaneously to achieve maximum energy output. Sun et al. [4] provided a global perspective on bifacial module optimization, evaluating combined effects of tilt angle, albedo, and latitude across diverse geographic locations. Their findings demonstrated that the relative importance of different installation parameters varies significantly with geographic location, underscoring the need for location-specific optimization tools.")
P("Ganesan et al. [20] conducted performance analysis of n-type PERT bifacial solar PV modules under diverse albedo conditions. Their experimental study investigated five different surfaces (grass, sand, cement, white paint, and aluminum) and found that aluminum surfaces give the best energy generation with an average bifacial gain of 21.4%. Pelaez et al. [21] compared five different bifacial irradiance models and validated them against field measurements, reporting that a bifacial gain of approximately 20% was attainable under specific configurations.")

H("2.6  Simulation and Modeling Approaches")
P("Accurate simulation of bifacial PV systems requires integration of solar radiation models, geometric view factor calculations, and electrical performance models. Liu and Jordan [15] developed the isotropic sky model forming the foundation for estimating tilted surface irradiance from horizontal measurements. This model decomposes global horizontal irradiance into beam, diffuse, and ground-reflected components, providing a practical framework for PV surface irradiance estimation.")
P("Beckman and Duffie [16] provided comprehensive analytical methods for solar engineering applications including detailed formulations for solar geometry calculations, irradiance decomposition, and tilted surface irradiance estimation. Marion et al. [17] developed a practical irradiance model specifically for bifacial PV modules, addressing shadow effects of module rows on the ground.")
P("Yusufoglu et al. [18] demonstrated a rigorous approach accounting for the shadow effect on ground-reflected irradiance based on the principle of the view factor from heat transfer fundamentals. Their model separates the GHI into diffuse and direct components, recognizing that the diffuse component remains unchanged while the direct portion of ground-reflected radiation is emitted only from the area outside the shadow. This methodology forms the basis of the rear-side irradiance model implemented in the present work.")

H("2.7  Research Gap Analysis")
P("Based on the comprehensive review of existing literature, several key research gaps have been identified:")
P("(i) Limited Combined Analysis: Most existing studies evaluate installation parameters independently rather than considering their combined influence. There is a need for frameworks that can simultaneously analyze the effects of tilt angle, albedo, and mounting height.")
P("(ii) Location-Specific Optimization: Many studies are limited to specific geographic locations or generalized climatic conditions. A flexible framework that can retrieve and utilize location-specific irradiance data for any given site is needed.")
P("(iii) Accessibility Gap: Current optimization approaches often require specialized software knowledge or access to commercial simulation tools, creating a barrier for many PV system designers.")
P("(iv) Dual Optimization Objectives: Few studies consider the trade-off between maximum total energy generation and maximum rear-side gain as separate but complementary optimization objectives.")
P("The present work addresses these gaps by developing a comprehensive computational framework that integrates location-specific solar irradiance data retrieval, rigorous mathematical modeling, and a user-friendly frontend platform for parametric analysis and optimization.")

TBL(["Surface Type","Albedo Value"],
    [["Urban environment","0.14-0.22"],["Grass","0.15-0.25"],["Fresh grass","0.26"],["Fresh snow","0.82"],["Wet snow","0.55-0.75"],["Dry asphalt","0.09-0.15"],["Wet asphalt","0.18"],["Concrete","0.25-0.35"],["Red tiles","0.33"],["Aluminum","0.85"],["Copper","0.74"],["New galvanized steel","0.35"],["Very dirty galvanized","0.08"]],
    "Table 2.1: Albedo Values of Common Surface Types for PV Applications [11]")
NL()

TBL(["Study","Parameters Analyzed","Key Findings","Limitation"],
    [["Guerrero-Lemus et al. [1]","Technology review","Comprehensive bifacial PV review","No parametric optimization"],
     ["Sun et al. [4]","Tilt, albedo, latitude","Global optimization perspective","No user-friendly tool"],
     ["Basak et al. [5]","Tilt angle","Bifacial optimal tilt differs from monofacial","Single parameter only"],
     ["Dincer & Ozer [11]","Albedo, tilt, height, mounting","21.2% rear gain for aluminum","Limited to Turkey"],
     ["Yusufoglu et al. [18]","Tilt, height, albedo","Up to 30% gain; log height dependence","Limited to Oslo/Cairo"],
     ["Patel et al. [14]","Tracking, geometry","Simultaneous optimization needed","Tracking systems only"]],
    "Table 2.2: Summary of Key Literature on Bifacial PV Parametric Studies")

doc.add_page_break()
doc.save('_part2.docx')
print("Ch2 done.")
